# Generated by Django 4.1.3 on 2022-11-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=200, null=True)),
                ('tripduration', models.CharField(max_length=200, null=True)),
                ('destination', models.CharField(max_length=1000, null=True)),
                ('price', models.FloatField(null=True)),
                ('image', models.ImageField(upload_to='pics')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.CharField(choices=[('Group', 'Group'), ('Solo', 'Solo'), ('Trekking', 'Trekking')], max_length=200, null=True)),
            ],
        ),
    ]
