# Generated by Django 4.1.3 on 2022-11-08 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('people', models.IntegerField()),
                ('order_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('pack_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Traveler.packages')),
            ],
        ),
    ]
