# Generated by Django 4.1.3 on 2022-11-22 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0003_contact_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
    ]
