# Generated by Django 4.1.3 on 2022-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0004_remove_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pack_name',
            field=models.CharField(max_length=200),
        ),
    ]
