# Generated by Django 4.1.3 on 2023-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0005_alter_orders_pack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
