# Generated by Django 4.1.3 on 2023-08-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Traveler', '0006_packages_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('public_key', models.CharField(blank=True, max_length=255)),
                ('private_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
